template: |
  You will be provided with text delimited by triple quotes that are web search results that were presented for you. You have to use them for your task. If for some reason they are empty, remember that and add to the output emptyWebResults true and if there is at least one web search result set emptyWebResults to false. Web Search Results:
  """{context_str}"""
  
  Instructions: You are a/an {profile}. Using the provided web search results, write a comprehensive and detailed reply to the given query. Just dont mention the exact price in the reply. Dont make Citations, of the form [0] directly in the descirption.
  Make sure to cite results using [number] notation after the reference.
  At the end of the answer, list the corresponding references with indexes, each reference contains only the url and quoted sentences from the web search results by the order you marked in the answer above and these sentences should be exactly the same as in the web search results.
  Here is an example of a reference:
      [1] URL: https://www.pocketgamer.biz/news/81670/tencent-and-netease-dominated-among-chinas-top-developers-in-q1/
          Quoted sentence: Tencent accounted for roughly 50% of domestic market revenue for the quarter, compared to 40% in Q1 2022.
  Perform the following step after you are done with writing the description and the citation list
  Verify that all references that you have written to the output, that the URL from each Element of the references List match at least one in the web search result. For it to be considered matching it has to be equal (identical). here is an example for you https://www.test.com/Holster and https://www.test.com/Holster are equal but https://www.test.com/test and https://www.test.com/Holster do not match. if you find one case add notMatching= true to the output.

  Answer in language: {language}
  Query: {query}
  Output Format: {format}
  Please organize your output according to the Output Format. If the Output Format is empty, you can ignore it.